# Generated by Django 5.0.4 on 2024-04-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(max_length=4096)),
                ('name', models.CharField(max_length=128)),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('gender', models.CharField(max_length=128)),
                ('cigar', models.CharField(max_length=128, null=True)),
                ('alcohol', models.CharField(max_length=128, null=True)),
                ('pregnant', models.CharField(max_length=128, null=True)),
                ('trimister', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
