# Generated by Django 5.0.4 on 2024-04-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payement_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payement_reference',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
