# Generated by Django 5.0.4 on 2024-04-07 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('id_on_store', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('popularity', models.IntegerField()),
                ('img', models.URLField()),
                ('details', models.TextField(max_length=1024)),
                ('description', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_created=True)),
                ('created', models.DateTimeField(auto_created=True)),
                ('nameOnStore', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('store', models.CharField(max_length=64)),
                ('relocate', models.URLField()),
                ('delivery_time', models.CharField(max_length=128)),
                ('delivery_details', models.TextField(max_length=1024)),
                ('shop_rating', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.product')),
            ],
        ),
    ]
