# Generated by Django 5.0.4 on 2024-04-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricelog',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
