# Generated by Django 5.0.4 on 2024-04-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0003_alter_product_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelog',
            name='shop_rating',
        ),
    ]
